### ISSUE TITLE
Include missing stamps

### ISSUE THREAD

**Issue by chq81** [kunicmarko20/jms-messenger-adapter#11]
Hi,
Symfony 4.3 provides a lot of different stamps.
Unfortunately not all of them can be serialized as they are missing from the serializer configuration.
These include:

- DelayStamp
- RedeliveryStamp
- HandledStamp
- SentToFailureTransportStamp
- TransportMessageIdStamp

Can you add them please?
Thanks a lot for your work!

**Comment by kunicmarko20** [comment]
Hey @chq81, thank you for the report, would be awesome if you can do a PR with config files? If not I will try to do it when I find some free time.

**Comment by chq81** [comment]
@kunicmarko20 Will do, just have to find some free time :)

Another question at this point. Currently I use https://github.com/sroze/messenger-enqueue-transport to be able to use Enqueue with Symfony messenger. In the latest version, the maintainer introduced a separate stamp.
What do you suggest who should hold the configuration for that?

**Comment by kunicmarko20** [comment]
I think this bundle should do that too, and enqueue adapter should be added as a dev dependency.

**Comment by chq81** [comment]
Alright, I will put that in as well.

**Comment by kunicmarko20** [comment]
https://github.com/kunicmarko20/jms-messenger-adapter/releases/tag/0.2.1 just tagged a new version
