### ISSUE TITLE
Encoded envelope should have at least a "body" and some "headers"

### ISSUE THREAD

**Issue by sanchobouillant** [kunicmarko20/jms-messenger-adapter#18]
Hi,

I copy/paste the code provided in the documentation. When I receive the message with my consumer I get the error

> [KunicMarko\JMSMessengerAdapter\Exception\ArgumentMissing]
>   Encoded envelope should have at least a "body" and some "headers".

> Exception trace:
>   at /var/application/vendor/kunicmarko/jms-messenger-adapter/src/Exception/ArgumentMissing.php:11
>  KunicMarko\JMSMessengerAdapter\Exception\ArgumentMissing::envelopeBodyAndHeaders() at /var/application/vendor/kunicmarko/jms-messenger-adapter/src/Serializer.php:32
>  KunicMarko\JMSMessengerAdapter\Serializer->decode() at /var/application/vendor/symfony/messenger/Transport/AmqpExt/AmqpReceiver.php:66
>  Symfony\Component\Messenger\Transport\AmqpExt\AmqpReceiver->getEnvelope() at /var/application/vendor/symfony/messenger/Transport/AmqpExt/AmqpReceiver.php:45
>  Symfony\Component\Messenger\Transport\AmqpExt\AmqpReceiver->get() at /var/application/vendor/symfony/messenger/Worker.php:78
>  Symfony\Component\Messenger\Worker->run() at /var/application/vendor/symfony/messenger/Command/ConsumeMessagesCommand.php:186
>  Symfony\Component\Messenger\Command\ConsumeMessagesCommand->execute() at /var/application/vendor/symfony/console/Command/Command.php:255
>  Symfony\Component\Console\Command\Command->run() at /var/application/vendor/symfony/console/Application.php:930
>  Symfony\Component\Console\Application->doRunCommand() at /var/application/vendor/symfony/framework-bundle/Console/Application.php:97
>  Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at /var/application/vendor/symfony/console/Application.php:264
>  Symfony\Component\Console\Application->doRun() at /var/application/vendor/symfony/framework-bundle/Console/Application.php:83
>  Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /var/application/vendor/symfony/console/Application.php:140
>  Symfony\Component\Console\Application->run() at /var/application/bin/console:42

- Symfony 5
- Messenger 5.0

**Comment by chq81** [comment]
@sanchobouillant Is this still relevant? Can you provide your message/envelope structure you send into the transport?

**Comment by sanchobouillant** [comment]
I fixed it 1 year ago. I don't remenber how :/

**Comment by chq81** [comment]
@sanchobouillant No worries, just wanted to check.
